name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: kvoon3/workflows/.github/workflows/pnpm-release.yml@main
    with:
      publish: true
      build: pnpm build

    permissions:
      contents: write
      id-token: write
